CRITICAL - 2023-01-10 04:06:56 --> Optional parameter $verbs declared before required parameter $to is implicitly treated as a required parameter
#0 C:\xampp\htdocs\ci4\system\Autoloader\Autoloader.php(365): CodeIgniter\Debug\Exceptions->errorHandler(8192, 'Optional parame...', 'C:\\xampp\\htdocs...', 1017)
#1 C:\xampp\htdocs\ci4\system\Autoloader\Autoloader.php(365): require_once()
#2 C:\xampp\htdocs\ci4\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('CodeIgniter\\Rou...')
#4 C:\xampp\htdocs\ci4\system\Config\Services.php(699): CodeIgniter\Autoloader\Autoloader->loadClass('CodeIgniter\\Rou...')
#5 C:\xampp\htdocs\ci4\system\Config\BaseService.php(123): CodeIgniter\Config\Services::routes(false)
#6 C:\xampp\htdocs\ci4\system\Config\Services.php(696): CodeIgniter\Config\BaseService::getSharedInstance('routes')
#7 C:\xampp\htdocs\ci4\app\Config\Routes.php(4): CodeIgniter\Config\Services::routes()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(782): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\public\index.php(46): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-01-10 04:06:56 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\ci4\app\Config\Events.php:33) in C:\xampp\htdocs\ci4\system\Debug\Exceptions.php:164
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 164)
#1 C:\xampp\htdocs\ci4\system\Debug\Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-01-10 04:18:47 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 04:27:25 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 04:47:54 --> Unable to connect to the database.
Main connection [MySQLi]: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 04:52:59 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 04:55:52 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 04:57:58 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 05:26:08 --> Unable to connect to the database.
Main connection [MySQLi]: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mitglieder` (`username`, `email`, `password`) VALUES (:username:, :email:, :password:)', [...], false)
 3 APPPATH\Models\MitgliederModel.php(39): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Login.php(62): App\Models\MitgliederModel->createPerson()
 5 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Login->create()
 6 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 08:43:07 --> Undefined index: id
in APPPATH/Views/todolist/person_edit.php on line 62.
 1 APPPATH/Views/todolist/person_edit.php(62): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: id', 'APPPATH/Views/todolist/person_edit.php', 62, [...])
 2 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/todolist/person_edit.php')
 3 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render('todolist/person_edit', [], true)
 5 APPPATH/Controllers/Personen.php(30): view('todolist/person_edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Personen->index()
 7 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personen))
 8 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-10 08:48:11 --> Undefined index: id
in APPPATH/Views/todolist/person_edit.php on line 62.
 1 APPPATH/Views/todolist/person_edit.php(62): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: id', 'APPPATH/Views/todolist/person_edit.php', 62, [...])
 2 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/todolist/person_edit.php')
 3 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render('todolist/person_edit', [], true)
 5 APPPATH/Controllers/Personen.php(30): view('todolist/person_edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Personen->index()
 7 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personen))
 8 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
